version: "3.8"

services:
  mysql57:
    image: mysql:8.0.29
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: privilege_management
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

  web:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:root@mysql57:3306/privilege_management
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
    depends_on:
      mysql57:
        condition: service_healthy
    restart: on-failure

volumes:
  db_data: